name: Build for aarch64

on:
  push:
    branches:
      - main  # 可以根据您的需求进行更改

jobs:
  build:
    runs-on: ubuntu-latest  # 使用Ubuntu作为构建环境

    strategy:
      matrix:
        go-version: [1.16]  # 可以根据您的项目需求选择合适的Go版本

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod download

    - name: Build for aarch64
      run: GOARCH=arm64 GOOS=linux go build -o myapp

    # 您可以在此处添加其他需要的步骤，例如测试、部署等

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-aarch64
        path: ./myapp
