name: Build for aarch64

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest  # 使用Ubuntu作为构建环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16  # 可以根据您的项目需求选择合适的Go版本

    - name: Install UPX (optional)
      run: |
        # 安装 UPX，用于压缩可执行文件
        wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
        tar -xf upx-3.96-amd64_linux.tar.xz
        sudo mv upx-3.96-amd64_linux/upx /usr/local/bin/
        rm -rf upx-3.96-amd64_linux*

    - name: chomd
      run: chmod +x buildARM.sh
      
    - name: Build for aarch64
      run: ./buildARM.sh

    # 您可以在此处添加其他需要的步骤，例如测试、部署等

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-aarch64
        path: ./myapp-aarch64
